version: "3.5"
services:
  cardano-node:
    build: .
    #image: koolwithk/cardano-node:1.35.5
    environment:
      NETWORK:
      CARDANO_NODE_SOCKET_PATH: "/ipc/node.socket"
    volumes:
      - node-${NETWORK}-db:/data
      - node-ipc:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

volumes:
  node-mainnet-db:
  node-testnet-db:
  node-preview-db:
  node-preprod-db:
  node-p2p-db:
  node-marlowe-pioneers-db:
  node-ipc:
  node-config:
